spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username=mini_dish_manager
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8085


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none